### ISSUE TITLE
Better type identification

### ISSUE THREAD

**Issue by hardenedapple** [hardenedapple/gdb-walkers#7]
At the moment I identify a type by just using `str(x.type)`.

I have a strong feeling this can be done better.

This method has known downsides when using arrays of temporary structures.
Maybe I should look into the gdb.types.get_basic_type function?

**Comment by mmalcomson** [comment]
In the `gdb-val-addr` branch (and the `gdb-values` branch) we now use `gdb.Values`, this means the type handling is done for us by GDB.
